# Generated by Django 2.0.5 on 2018-08-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('screen_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_name', models.CharField(max_length=10)),
                ('track', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='extension',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='artistfk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
            preserve_default=False,
        ),
    ]
