# Generated by Django 2.0.5 on 2018-08-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180821_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
