# Generated by Django 2.0.5 on 2018-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180821_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='play_name',
            field=models.CharField(max_length=20),
        ),
    ]
