# Generated by Django 2.0.5 on 2018-10-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20181020_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(default='22', on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.IntegerField(default=0),
        ),
    ]
